<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Mnews extends CI_Controller {
    const TBL_NEWS = "news";
	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see http://codeigniter.com/user_guide/general/urls.html
	 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->model('newsmodel');

    }


    public function index()
	{

        $this->load->library('pagination');
        $config['base_url'] = base_url().'index.php/Mnews/index/';
        $config['total_rows'] = $this->db->count_all(self::TBL_NEWS);
        $config['per_page'] = 5;
//        $config['full_tag_open'] = '<li >';
//        $config['full_tag_close'] = '</li>';
        $config['first_link'] = '首页';
        $config['first_tag_open'] = '<li >';//“第一页”链接的打开标签。
        $config['first_tag_close'] = '</li>';//“第一页”链接的关闭标签。
        $config['last_link'] = '尾页';//你希望在分页的右边显示“最后一页”链接的名字。
        $config['last_tag_open'] = '<li>';//“最后一页”链接的打开标签。
        $config['last_tag_close'] = '</li>';//“最后一页”链接的关闭标签。
        $config['next_link'] = '下一页';//你希望在分页中显示“下一页”链接的名字。
        $config['next_tag_open'] = '<li>';//“下一页”链接的打开标签。
        $config['next_tag_close'] = '</li>';//“下一页”链接的关闭标签。
        $config['prev_link'] = '上一页';//你希望在分页中显示“上一页”链接的名字。
        $config['prev_tag_open'] = '<li>';//“上一页”链接的打开标签。
        $config['prev_tag_close'] = '</li>';//“上一页”链接的关闭标签。
        $config['cur_tag_open'] = '<li class="active"><a href="#">';//“当前页”链接的打开标签。
        $config['cur_tag_close'] = '</a></li>';//“当前页”链接的关闭标签。
        $config['num_tag_open'] = '<li>';//“数字”链接的打开标签。
        $config['num_tag_close'] = '</li>';

        $this->pagination->initialize($config);

        $data['news'] = $this->newsmodel->get_news($config['per_page'],$this->uri->segment(3));
        $this->load->view('m_news',$data);

    }
}
