<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Mnewsdetail extends CI_Controller {
    const TBL_NEWS = "news";
	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see http://codeigniter.com/user_guide/general/urls.html
	 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->model('newsmodel');

    }


    public function index()
	{
        $this->newsmodel->update_count($this->uri->segment(3));
        $data['news'] = $this->newsmodel->get_newsbyid($this->uri->segment(3));
        $this->load->view('m_news_detail',$data);
    }
}
