<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Newsinput extends CI_Controller {

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see http://codeigniter.com/user_guide/general/urls.html
	 */
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->model('newsmodel');
    }


    public function index()
	{

//        $this->pageviewmodel->set_pvs();
//
//        $data['pv']=$this->pageviewmodel->get_count();
        $this->load->helper('form');
        $this->load->library('form_validation');

        $this->form_validation->set_rules('title', 'Title', 'required');
        $this->form_validation->set_rules('summary', 'Summary', 'required');
        $this->form_validation->set_rules('content', 'Content', 'required');

        if ($this->form_validation->run() === FALSE)
        {

            $this->load->view('news_input');

        }
        else
        {
            $this->newsmodel->set_news();
            $data['success']="成功创建新闻";
            $this->load->view('news_input',$data);
        }
	}
}
